version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres:11
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    command: -p ${DB_PORT}
